version: '3'
services:
  couchdb:
    image: couchdb:3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb-data:/opt/couchdb/data
      - couchdb-etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984

volumes:
  couchdb-data: {}
  couchdb-etc: {}
